version: '3.2'

services:

  athena:
    build: ./athena
    image: athena
    container_name: athena
    expose:
      - 5001
    working_dir: /app/athena
    command: python main.py
    volumes:
      - .:/app

  rest:
    build: ./rest
    image: rest
    container_name: rest
    environment:
      - ATHENA_BASE_URL=http://athena:5001
    expose:
      - 5000
    working_dir: /usr/src/app/rest
    command: python manage.py runserver --host 0.0.0.0 --debug
    volumes:
      - .:/usr/src/app
    depends_on:
      - athena

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - rest

