version: '3.2'

services:

  athena:
    build:
      context: athena/
    restart: always
    ports:
      - "5001:5001"
    networks:
      - sentient

  rest:
    build: ./rest
    image: rest
    container_name: rest
    expose:
      - 5000
    working_dir: /usr/src/app/rest
    command: python manage.py runserver --host 0.0.0.0 --debug
    volumes:
      - .:/usr/src/app
    depends_on:
      - athena

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - rest

networks:
  sentient:
    driver: bridge

