swagger: '2.0'
info:
  description: |
    This is social server.
  version: 1.0.0
  title: Swagger Social
  contact:
    email: sinakhorami94@gmail.com
tags:
  - name: instagram
    description: Instagram Post Comments
  - name: telegram
    description: Telegram Channel Posts
  - name: twitter
    description: Twitter User Timeline
  - name: web
    description: KhabarFouri Post Comments
paths:
  /instagram/{shortcode}:
    get:
      tags:
        - instagram
      summary: Get comments of an instagram post
      description: Returns list of comments and paging option
      produces:
        - application/json
      parameters:
        - name: shortcode
          in: path
          description: unique shortcode of an instagram post
          required: true
          type: string
        - name: end_cursor
          in: query
          description: end_cursor to use in pagination
          required: false
          type: string
      responses:
        200:
          description: successful operation
        400:
          description: Invalid shortcode
  /telegram/{username}:
    get:
      tags:
        - telegram
      summary: Get posts of a telegram channel
      description: Returns list of messages
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          description: unique username of telegram channel
          required: true
          type: string
        - name: offset_id
          in: query
          description: offset_id to use in pagination
          required: false
          type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Message'
        400:
          description: Invalid input
  /twitter/{username}:
    get:
      tags:
        - twitter
      summary: Get statuses of a twitter account
      description: Returns list of tweets
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          description: unique username of twitter account
          required: true
          type: string
        - name: max_id
          in: query
          description: max_id to use in pagination (get older tweets)
          required: false
          type: string
        - name: since_id
          in: query
          description: since_id to use in pagination (get newer tweets)
          required: false
          type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Tweet'
        400:
          description: Invalid input
  /web/khabar-foori:
    get:
      tags:
        - web
      summary: Get comments of khabar-foori web post
      description: Returns list of comments
      produces:
        - application/json
      parameters:
        - name: url
          in: query
          description: url of khabar-foori post
          required: true
          type: string
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/WebComment'
        404:
          description: Page Not Found!
definitions:
  Message:
    type: object
    properties:
      messages:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              format: int64
            date:
              type: integer
              format: int64
            link:
              type: string
            views:
              type: integer
              format: int64
            text:
              type: string
            sentiment:
              type: string
              description: Sentiment Tag
              enum:
                - pos
                - neu
                - neg
  Tweet:
    type: object
    properties:
      tweets:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            created_at:
              type: string
              format: date-time
            type:
              type: string
              description: Tweet Type
              enum:
                - tweet
                - retweet
                - quote
                - reply
            favorite_count:
              type: integer
            retweet_count:
              type: integer
            text:
              type: string
            sentiment:
              type: string
              description: Sentiment Tag
              enum:
                - pos
                - neu
                - neg
            user:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                screen_name:
                  type: string
                description:
                  type: string
                avatar:
                  type: string
                followers_count:
                  type: integer
                followings_count:
                  type: integer
                statuses_count:
                  type: integer
  WebComment:
    type: object
    properties:
      comments:
        type: array
        items:
          type: object
          properties:
            author:
              type: string
            date:
              type: string
              format: date-time
            neg:
              type: string
              description: dislike count
            pos:
              type: string
              description: like count
            text:
              type: string
            sentiment:
              type: string
              description: Sentiment Tag
              enum:
                - pos
                - neu
                - neg
            replays:
              type: array
              description: List of comment replays
              items:
                type: object
# host: localhost:5000
# basePath: /api
# schemes:
#  - http
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /SinaKhorami/Sentient/1.0.0
schemes:
 - https
 - http